micronaut:
  application:
    name: iotBackupManager

application:
  drive-credentials-directory: ${DRIVE_CREDENTIALS_DIR}
  drive-target-directory: ${DRIVE_TARGET_DIR}
  tasmota-ip-addresses: ${TASMOTA_IP_ADDRESSES}
  backup-directories: ${BACKUP_DIRS}
